set-option -g default-terminal "screen-256color"
set -g mouse on
set -g prefix C-s

# vim bindings
setw -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# stop normal mode switching lines
set -sg escape-time 0 
set -g status-interval 0

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'chistoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "time"

set -g status-position top

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
